### ISSUE TITLE
gulp test returns 325 error from PhantomJS

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-ui#5] opened 2018-11-19 11:56 UTC
Probably the same issue is causing all those errors... Something about angular
In regard of the very first error: the directory `matchminer-ui/app` does exist, but` matchminer-ui/app/assets` does not 

My setup: 

Mac OSX El Capitan 10.11.6 
```
$ node --version
v10.12.0

$gulp --version
[12:49:00] CLI version 3.9.1
[12:49:00] Local version 3.9.1

$ phantomjs -v
2.1.1
```
------------------------
`$ gulp test`

> 12:52:12] Using gulpfile ~/matchminer-ui/gulpfile.js
> [12:52:12] Starting 'config'...
> [12:52:12] Starting 'scripts'...
> [12:52:12] Finished 'config' after 204 ms
> [12:52:13] all files 542.39 kB
> [12:52:13] Finished 'scripts' after 1.53 s
> [12:52:13] Starting 'test'...
> 19 11 2018 12:52:14.037:WARN [watcher]: Pattern "/Users/ipozdnya/matchminer-ui/app/**/*.module.js" does not match any file.
> 19 11 2018 12:52:14.194:WARN [watcher]: Pattern "/Users/ipozdnya/matchminer-ui/app/assets/**/*" does not match any file.
> 19 11 2018 12:52:15.204:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
> 19 11 2018 12:52:15.206:INFO [launcher]: Starting browser PhantomJS
> 19 11 2018 12:52:15.968:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket FTBB7xliHvnybVH1AAAA with id 30323069
> **PhantomJS 2.1.1 (Mac OS X 0.0.0) Controller: ClinicalTrialsCtrl should be set the isAuthenticated parameter on init FAILED**
> 	/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4588:53
> 	forEach@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:322:24
> 	loadModules@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4548:12
> 	createInjector@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4470:30
> 	workFn@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2954:60
> 	inject@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2934:46
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:40:9
> 	TypeError: undefined is not an object (evaluating 'ctrl.isAuthenticated') in /Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js (line 57)
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:57:14
> **PhantomJS 2.1.1 (Mac OS X 0.0.0) Controller: ClinicalTrialsCtrl should be able to detect changes of the searchterm in the elasticsearchservice and update the metadata FAILED**
> 	/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4588:53
> 	forEach@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:322:24
> 	loadModules@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4548:12
> 	createInjector@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4470:30
> 	workFn@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2954:60
> 	inject@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2934:46
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:40:9
> 	TypeError: undefined is not an object (evaluating 'ctrl.searchTerm') in /Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js (line 61)
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:61:14
> **PhantomJS 2.1.1 (Mac OS X 0.0.0) Controller: ClinicalTrialsCtrl should be able to detect changes of the  loading indicator used in the clinicaltrialsservice FAILED**
> 	/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4588:53
> 	forEach@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:322:24
> 	loadModules@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4548:12
> 	createInjector@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4470:30
> 	workFn@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2954:60
> 	inject@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2934:46
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:40:9
> 	TypeError: undefined is not an object (evaluating 'ctrl.isLoading') in /Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js (line 72)
> 	/Users/ipozdnya/matchminer-ui/app/scripts/app/clinical-trials/clinical-trials.controller.spec.js:72:14
> 
> 
> ... ANOTHER 320 ERRORS HERE...
> 
> 
> **PhantomJS 2.1.1 (Mac OS X 0.0.0) Various utilities function and filters should return the normal string when value is non negating FAILED**
> 	/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4588:53
> 	forEach@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:322:24
> 	loadModules@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4548:12
> 	createInjector@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4470:30
> 	workFn@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2954:60
> 	inject@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2934:46
> 	/Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js:24:9
> 	TypeError: undefined is not a constructor (evaluating 'filter('transformNegation')') in /Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js (line 88)
> 	/Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js:88:33
> **PhantomJS 2.1.1 (Mac OS X 0.0.0) Various utilities function and filters should be able to parse and transform comments FAILED**
> 	/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4588:53
> 	forEach@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:322:24
> 	loadModules@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4548:12
> 	createInjector@/Users/ipozdnya/matchminer-ui/bower_components/angular/angular.js:4470:30
> 	workFn@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2954:60
> 	inject@/Users/ipozdnya/matchminer-ui/bower_components/angular-mocks/angular-mocks.js:2934:46
> 	/Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js:24:9
> 	TypeError: undefined is not a constructor (evaluating 'filter('parsecomments')') in /Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js (line 95)
> 	/Users/ipozdnya/matchminer-ui/app/scripts/components/utilities/utilities.filters.spec.js:95:29
> **PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 325 of 325 (325 FAILED) ERROR (2.171 secs / 0 secs)**
> [12:52:19] 'test' errored after 5.6 s
> [12:52:19] Error: Failed 1 tests.
>     at /Users/ipozdnya/matchminer-ui/gulp/unit-tests.js:54:20
>     at removeAllListeners (/Users/ipozdnya/matchminer-ui/node_modules/karma/lib/server.js:336:7)
>     at Server.<anonymous> (/Users/ipozdnya/matchminer-ui/node_modules/karma/lib/server.js:347:9)
>     at Object.onceWrapper (events.js:273:13)
>     at Server.emit (events.js:187:15)
>     at emitCloseNT (net.js:1618:8)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ethansiegl** [comment] 2018-11-19 21:49
I'm sorry but I'm not able to reproduce this problem. It looks like there's a missing directory?

**Comment by cegg** [comment] 2018-12-31 16:16
Hello Ethan, I am trying again to do a docker build of matchminer-ui. 
I cloned it, cd into it and ran : $docker build -t matchminer-ui .

The first error is from “RUN gulp test” line in Dockerfile:
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 325 of 325 (325 FAILED) ERROR (2.382 secs / 0 secs)
[15:48:20] 'test' errored after 5.63 s
[15:48:20] Error: Failed 1 tests.
    at /usr/src/app/gulp/unit-tests.js:54:20
    at removeAllListeners (/usr/src/app/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/usr/src/app/node_modules/karma/lib/server.js:347:9)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1577:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
 
..and when I comment that line out it fails with this:
 
```
Removing intermediate container d46b5e7777ed
---> a705131d409c
Step 10/10 : COPY dist /var/www/apache-flask/api/static
COPY failed: stat /var/lib/docker/tmp/docker-builder911759571/dist: no such file or directory
```
It looks different from that phantom/bower issues I had before so I hope it's OK I bother you again with this.
Igor

**Comment by ethansiegl** [comment] 2018-12-31 18:42
Hello. No worries. This dockerfile really should not have been committed to this repo as it is packaging the UI code to work inside a static directory of the API code which is a holdover from a previous way the application was configured.

If you are really intent on using docker to run the UI standalone, you can try replacing the dockerfile with this: 
`# pull base node image.
FROM node:7

# add the npm dependencies and install
COPY ["package.json", "bower.json", "package-lock.json", "/"]
WORKDIR /
RUN npm install

# install bower and gulp globally
RUN npm install -g gulp-cli bower
RUN bower install --config.interactive=false  --allow-root

# add files to context
COPY app /app
COPY gulp /gulp
COPY gulpfile.js /gulpfile.js
COPY properties /properties

# serve it
RUN gulp serve`

**Comment by cegg** [comment] 2018-12-31 19:11
Thank you, will try and let you know!

**Comment by cegg** [comment] 2019-01-02 09:33
Tired with the file you poster.

The docker build run ends like this:

```
[09:19:23] Starting 'serve'...
[09:19:23] 'serve' errored after 945 μs
[09:19:23] Error: ENOENT: no such file or directory, open '../certificates/matchminer.key'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at browserSyncInit (/gulp/server.js:52:12)
    at Gulp.<anonymous> (/gulp/server.js:100:2)
    at module.exports (/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/node_modules/orchestrator/index.js:214:10)
    at /node_modules/orchestrator/index.js:279:18
    at finish (/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/node_modules/orchestrator/index.js:214:10)
    at /node_modules/orchestrator/index.js:279:18
    at finish (/node_modules/orchestrator/lib/runTask.js:21:8)
    at /node_modules/orchestrator/lib/runTask.js:52:4
    at f (/node_modules/end-of-stream/node_modules/once/once.js:17:25)
```

**Comment by cegg** [comment] 2019-01-03 15:35
A colleague suggested that I might have to get a certificate from the software maker since there's no `certificates/matchminer.key` file in the git repository, I am talking about this error line:

`[16:14:33] Error: ENOENT: no such file or directory, open '../certificates/matchminer.key' `

**Comment by cegg** [comment] 2019-01-04 12:00
I generated matchminer.key and matchminer.crt with openssl and got the web server running finally. Got the front page in the browser. Now have to figure out how the rest.. Thanks!

**Comment by ethansiegl** [comment] 2019-01-04 14:40
Sorry for the delayed response. Glad you got it working! If you don't mind, could you submit a PR with the commands you used to generate the certs and the dockerfile update?

Also, there is a slack channel for the open source efforts - it's cbioportal.slack.com and the room is matchminer-oncokb. There are a few other groups there who have also been working on getting a local instance of Matchminer up and running, and if I am unavailable to respond it might be worth it to ping the channel also to see if anyone else can lend a hand

**Comment by cegg** [comment] 2019-01-04 17:44
I submitted a pul request for the README.md in regard of the certificates. I will submit another one for Dockerfile once I am sure the whole Dockerfile sequence works for me. So far the certificate generation added to Dockerfile as I had it in the README.md works fine, but now `docker build` run  it end with  the next error: 

> Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

And there is one more issue from `gulp serve` about http vs. https, I will open a separate issue about that one.

**Comment by ethansiegl** [comment] 2019-01-15 22:02
sorry for the very delayed response! 

I would say if you could submit the newer Dockerfile which works, that would be great 👍Will close this issue as it seems like the original problem was solved

**Closed by ethansiegl** 2019-01-15 22:02 UTC
